### ISSUE TITLE
build issue with Japanese system - compiler errors C2001 & C2143

### ISSUE THREAD

**Issue by makorin0315** [intersystems/iknow#23] opened 2020-05-13 16:19 UTC
This issue happens when building iKnowEngineTest or iKnowALI on Japanese Windows and Japanese Visual Studio that gets installed, basically the setup that would be used by most Japanese users.

Error C2001 - newline in constant
Error C2143 - missing ')' before 'if'
Error C2143 - missing ';' before 'if'

These errors occur in the file enginetest.cpp for the line that starts with `if (language_code == "ja") return`. It fails because of the Japanese text. I've found that some very short text may work, but they are certainly not long enough to be called sentences:

お金 - works
お金をなくした - doesn't work
コーヒー - works
コーヒー代 - works
テキスト - doesn't work
ＡＢＣＺ - works (all double-width characters)
ＡＢＣＺ。 - doesn't work (same as above)
雅子 - doesn't work
まさこ - works

**Comment by makorin0315** [comment] 2020-05-13 17:34
I have an update on this one as well - if I re-save the enginetest.cpp file with "UTF-8 (With Signature)", the build completes without above errors. However, I now have more Warnings than before - 45 if I save with BOM & 33 when the file is without BOM. The warnings that only appear with BOM file are all C4566 - "character represented by universal-character-name 'UNICODE (i.g., \u00F3)' cannot be represented in the current code page (932)." These warnings appear for lines for language_code = es, pt, sv, uk, cs.

**Comment by bdeboe** [comment] 2020-05-15 12:44
Feels like a duplicate of #22 . We may just have to re-save all (?) our source files with the right BOM. Not sure if it also applies to files that are generated as part of the language model compilation, but perhaps @makorin0315 already tested that?

**Comment by makorin0315** [comment] 2020-05-15 12:54
@bdeboe, I created 2 separate issues per Jos's suggestion. FYI.

**Comment by JosDenysGitHub** [comment] 2020-08-20 18:09
The problem is solved using the "u8" string literal directive (from C++11), for some reason visual studio tries to convert string literals to the OS string encoding, and that did not work well Japanese text. "u8" means : this is utf8 encoded, and don't touch it !

**Closed by JosDenysGitHub** 2020-08-20 18:09 UTC
Labels: bug, duplicate
